apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dummy-service
  description: A dummy service for testing Backstage catalog import
  tags:
    - test
    - dummy
spec:
  type: service
  lifecycle: experimental
  owner: user:chkutti
